"""Builders for S1 pending-open instructions."""

from __future__ import annotations

from typing import Any, Mapping

import numpy as np
import pandas as pd

from open_execution import safe_float


S1_CANDIDATE_FLOAT_FIELDS = (
    "premium_stress",
    "theta_stress",
    "premium_margin",
    "premium_yield_margin",
    "premium_yield_notional",
    "rv_ref",
    "iv_rv_spread_candidate",
    "iv_rv_ratio_candidate",
    "variance_carry",
    "breakeven_price",
    "breakeven_cushion_abs",
    "breakeven_cushion_iv",
    "breakeven_cushion_rv",
    "iv_shock_loss_5_cash",
    "iv_shock_loss_10_cash",
    "premium_to_iv5_loss",
    "premium_to_iv10_loss",
    "premium_to_stress_loss",
    "theta_vega_efficiency",
    "gamma_rent_cash",
    "gamma_rent_penalty",
    "fee_ratio",
    "slippage_ratio",
    "friction_ratio",
    "premium_quality_score",
    "premium_quality_rank_in_side",
    "iv_rv_carry_score",
    "breakeven_cushion_score",
    "premium_to_iv_shock_score",
    "premium_to_stress_loss_score",
    "theta_vega_efficiency_score",
    "cost_liquidity_score",
    "b3_forward_variance_pressure",
    "b3_vol_of_vol_proxy",
    "b3_vov_trend",
    "b3_iv_shock_coverage",
    "b3_joint_stress_coverage",
    "b3_vomma_cash",
    "b3_vomma_loss_ratio",
    "b3_skew_steepening",
    "liquidity_score",
    "volume",
    "open_interest",
    "moneyness",
    "abs_delta",
    "delta",
    "gamma",
    "vega",
    "theta",
    "contract_iv",
    "contract_iv_change_1d",
    "contract_iv_change_3d",
    "contract_iv_change_5d",
    "contract_iv_change_for_vega",
    "contract_iv_skew_to_atm",
    "contract_skew_change_for_vega",
    "contract_price_change_1d",
    "b4_contract_score",
    "b6_contract_score",
    "b6_premium_to_stress_score",
    "b6_premium_to_iv10_score",
    "b6_theta_per_vega_score",
    "b6_theta_per_gamma_score",
    "b6_tail_move_coverage_score",
    "b6_vomma_score",
    "b6_premium_yield_margin_score",
)

S1_SIDE_META_FIELDS = (
    "b3_clean_vega_score",
    "b3_forward_variance_score",
    "b3_vol_of_vol_score",
    "b3_iv_shock_score",
    "b3_joint_stress_score",
    "b3_vomma_score",
    "b3_skew_stability_score",
    "b2_product_score",
    "b2_product_equal_budget_pct",
    "b2_product_quality_budget_pct",
    "b2_product_final_budget_pct",
    "b2_product_budget_mult",
    "b3_product_side_score",
    "b3_side_equal_budget_pct",
    "b3_side_quality_budget_pct",
    "b3_side_final_budget_pct",
    "b3_side_budget_mult",
    "b3_clean_vega_tilt_strength",
    "b4_product_side_score",
    "b4_side_equal_budget_pct",
    "b4_side_quality_budget_pct",
    "b4_side_final_budget_pct",
    "b4_side_budget_mult",
    "b4_product_tilt_strength",
    "b4_side_vov_penalty_mult",
    "b6_product_score",
    "b6_product_side_score",
    "b6_product_equal_budget_pct",
    "b6_product_quality_budget_pct",
    "b6_product_final_budget_pct",
    "b6_product_budget_mult",
    "b6_side_equal_budget_pct",
    "b6_side_quality_budget_pct",
    "b6_side_final_budget_pct",
    "b6_side_budget_mult",
    "b6_product_tilt_strength",
    "b6_side_tilt_strength",
    "b6_side_direction_penalty_mult",
)

S1_SIDE_META_WITH_CANDIDATE_FALLBACK = (
    "b4_premium_to_iv10_score",
    "b4_premium_to_stress_score",
    "b4_premium_yield_margin_score",
    "b4_gamma_rent_score",
    "b4_vomma_score",
    "b4_breakeven_cushion_score",
    "b4_vol_of_vol_score",
)


def selection_score(row: Mapping[str, Any]) -> float:
    value = row.get("quality_score", np.nan)
    return float(value) if pd.notna(value) else np.nan


def build_s1_sell_pending_item(
    *,
    row: Mapping[str, Any],
    product: str,
    option_type: str,
    mult: float,
    expiry: Any,
    mr: float,
    exchange: str,
    date_str: str,
    group_id: str,
    quantity: int,
    single_margin: float,
    new_greeks: Mapping[str, float],
    one_stress_loss: float,
    total_stress_loss: float,
    open_fee_per_contract: float,
    close_fee_per_contract: float,
    roundtrip_fee_per_contract: float,
    iv_state: Mapping[str, Any],
    side_meta: Mapping[str, Any],
    side_budget_mult: float,
    max_candidates: int,
    max_delta_gap: float,
    max_qty: int,
    current_vol_regime: str,
    effective_strategy_cap: float,
    product_budget_fields: Mapping[str, Any],
    stress_budget_pct: float,
) -> dict:
    item = {
        "strat": "S1",
        "product": product,
        "code": row["option_code"],
        "opt_type": option_type,
        "strike": row["strike"],
        "ref_price": row["option_close"],
        "n": int(quantity),
        "mult": mult,
        "expiry": expiry,
        "mr": mr,
        "role": "sell",
        "spot": row["spot_close"],
        "exchange": exchange,
        "group_id": group_id,
        "underlying_code": row.get("underlying_code"),
        "signal_date": date_str,
        "margin": single_margin * quantity,
        "cash_vega": new_greeks["cash_vega"],
        "cash_gamma": new_greeks["cash_gamma"],
        "one_contract_stress_loss": one_stress_loss,
        "stress_loss": total_stress_loss,
        "one_contract_margin": single_margin,
        "gross_premium_cash": safe_float(row.get("option_close", np.nan), np.nan) * float(mult) * quantity,
        "net_premium_cash": safe_float(row.get("net_premium_cash", np.nan), np.nan) * quantity,
        "open_fee_per_contract": open_fee_per_contract,
        "close_fee_per_contract": close_fee_per_contract,
        "roundtrip_fee_per_contract": roundtrip_fee_per_contract,
        "selection_score": selection_score(row),
        "vol_regime": current_vol_regime,
        "entry_atm_iv": iv_state.get("atm_iv", np.nan),
        "entry_iv_pct": iv_state.get("iv_pct", np.nan),
        "entry_iv_trend": iv_state.get("iv_trend", np.nan),
        "entry_rv_trend": iv_state.get("rv_trend", np.nan),
        "entry_iv_rv_spread": iv_state.get("iv_rv_spread", np.nan),
        "entry_iv_rv_ratio": iv_state.get("iv_rv_ratio", np.nan),
        "trend_state": side_meta.get("trend_state", row.get("trend_state", "")),
        "trend_score": side_meta.get("trend_score", row.get("trend_score", np.nan)),
        "trend_confidence": side_meta.get("trend_confidence", row.get("trend_confidence", np.nan)),
        "trend_range_position": side_meta.get(
            "trend_range_position",
            row.get("trend_range_position", np.nan),
        ),
        "trend_range_pressure": side_meta.get(
            "trend_range_pressure",
            row.get("trend_range_pressure", ""),
        ),
        "trend_role": side_meta.get("trend_role", row.get("trend_role", "")),
        "side_score_mult": side_meta.get("score_mult", row.get("side_score_mult", np.nan)),
        "side_budget_mult": side_budget_mult,
        "side_delta_cap": side_meta.get("delta_cap", np.nan),
        "ladder_candidate_count": max_candidates,
        "ladder_delta_gap": max_delta_gap,
        "effective_s1_stress_max_qty": max_qty,
    }
    for field in S1_CANDIDATE_FLOAT_FIELDS:
        item[field] = safe_float(row.get(field, np.nan), np.nan)
    for field in S1_SIDE_META_FIELDS:
        item[field] = side_meta.get(field, np.nan)
    for field in S1_SIDE_META_WITH_CANDIDATE_FALLBACK:
        item[field] = side_meta.get(field, safe_float(row.get(field, np.nan), np.nan))
    item.update(product_budget_fields)
    item["effective_strategy_margin_cap"] = effective_strategy_cap
    item["effective_s1_stress_budget_pct"] = stress_budget_pct
    return item
